version: "3"

services:
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - openendoint-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 30s
      start_period: 5s
      timeout: 1s
    networks:
      - openendpoint-tools
    restart: always

  api:
    build: api
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - openendpoint-tools
    depends_on:
      db:
        condition: service_healthy
      polypong:
        condition: service_completed_successfully
    restart: always

  polypong:
    build: polypong
    init: true
    environment:
      - NODE_ENV=production
    volumes:
      - ./polypong/static:/polypong/static
    networks:
      - openendpoint-tools

volumes:
  openendoint-db:

networks:
  openendpoint-tools:
