version: "3"

services:
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - openendoints-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 30s
      start_period: 5s
      timeout: 1s
    networks:
      - openendpoint-tools
    restart: always

  app:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    networks:
      - openendpoint-tools
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  openendoints-db:

networks:
  openendpoint-tools:
