name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup V
        uses: vlang/setup-v@v1
      - name: Check formatting
        run: v fmt -verify api

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        run: |
          echo "POSTGRES_USER=ghaction" > .env
          echo "POSTGRES_PASSWORD=testing" >> .env
          echo "POSTGRES_DB=ghaction" >> .env
          echo "PGHOST=db" >> .env
          echo "PGUSER=ghaction" >> .env
          echo "PGPASSWORD=testing" >> .env
          echo "PGDATABASE=ghaction" >> .env
      - name: Build static files
        run: docker compose run --rm polypong
      - name: Run tests
        run: docker compose run --rm api ./scripts/tests.sh
